version: '3.1'
services:            
    api:
        build: docker/api
        depends_on: 
            - db
            - mailcatcher
        env_file: ./.env
        ports:
            - "9000:80"
        volumes:
            - ./api:/var/www/html
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: ${MYSQL_DATABASE}
            DB_USERNAME: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
            TZ: Etc/GMT

    mailcatcher:
        image: yappabe/mailcatcher
        ports:
            - "2525:1025"
            - "9001:1080"
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - "mysql_data:/var/lib/mysql"
            - "./dump:/docker-entrypoint-initdb.d"

    couchdb:
        image: docker.io/bitnami/couchdb:3-debian-10
        environment:
            - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
        ports:
            - '5984:5984' 
            - '4369:4369' # FIXME Don't expose any admin ports
            - '9100:9100' # FIXME Don't expose any admin ports
        volumes:
            - couchdb_data:/bitnami/couchdb
            - ./docker/couchdb/sociocracy30-local.ini:/opt/bitnami/couchdb/etc/local.d/sociocracy30-local.ini
        
volumes:
    couchdb_data:
        driver: local
    mysql_data:
        driver: local
